export interface DadataSuggestion {

  "value": string,
  "unrestricted_value": string,
  "data": {
  "postal_code": string,
    "country": string,
    "country_iso_code": string,
    "federal_district": string,
    "region_fias_id": string,
    "region_kladr_id": string,
    "region_iso_code": string,
    "region_with_type": string,
    "region_type": string,
    "region_type_full": string,
    "region": string,
    "area_fias_id": string | null,
    "area_kladr_id": string | null,
    "area_with_type": string | null,
    "area_type": string | null,
    "area_type_full": string | null,
    "area": string | null,
    "city_fias_id": string,
    "city_kladr_id": string | null,
    "city_with_type": string,
    "city_type": string,
    "city_type_full": string,
    "city": string,
    "city_area": string | null,
    "city_district_fias_id": string | null,
    "city_district_kladr_id": string | null,
    "city_district_with_type": string | null,
    "city_district_type": string | null,
    "city_district_type_full": string | null,
    "city_district": string | null,
    "settlement_fias_id": string | null,
    "settlement_kladr_id": string | null,
    "settlement_with_type": string | null,
    "settlement_type": string | null,
    "settlement_type_full": string | null,
    "settlement": string | null,
    "street_fias_id": string | null,
    "street_kladr_id": string | null,
    "street_with_type": string | null,
    "street_type": string | null,
    "street_type_full": string | null,
    "street": string | null,
    "stead_fias_id": string | null,
    "stead_cadnum": string | null,
    "stead_type": string | null,
    "stead_type_full": string | null,
    "stead": string | null,
    "house_fias_id": string | null,
    "house_kladr_id": string | null,
    "house_cadnum": string | null,
    "house_flat_count": string | null,
    "house_type": string | null,
    "house_type_full": string | null,
    "house": string | null,
    "block_type": string | null,
    "block_type_full": string | null,
    "block": string | null,
    "entrance": string | null,
    "floor": null,
    "flat_fias_id": null,
    "flat_cadnum": null,
    "flat_type": null,
    "flat_type_full": null,
    "flat": null,
    "flat_area": null,
    "square_meter_price": null,
    "flat_price": null,
    "room_fias_id": null,
    "room_cadnum": null,
    "room_type": null,
    "room_type_full": null,
    "room": null,
    "postal_box": null,
    "fias_id": string,
    "fias_code": null,
    "fias_level": string,
    "fias_actuality_state": "0",
    "kladr_id": "7800000000000",
    "geoname_id": "498817",
    "capital_marker": "0",
    "okato": "40000000000",
    "oktmo": "40000000",
    "tax_office": "7800",
    "tax_office_legal": "7800",
    "timezone": null,
    "geo_lat": "59.9390012",
    "geo_lon": "30.3158184",
    "beltway_hit": null,
    "beltway_distance": null,
    "metro": null,
    "divisions": null,
    "qc_geo": "4",
    "qc_complete": null,
    "qc_house": null,
    "history_values": [
    string
  ],
    "unparsed_parts": string | null,
    "source": string | null,
    "qc": string | null
}
}
